# Generated by Django 3.1.7 on 2021-04-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Страна производства'),
        ),
    ]
